<?php

use Illuminate\Database\Seeder;

class OnlineContentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('online_contents')->insert([
            [
                'caption' => "Angular Crash Course",
                'description' => "iIn this video we will talk about what Angular is and then jump in and build a small app With Angular 7, looking at most of the ...",
                'url' => "https://www.youtube.com/watch?v=Fdf5aTYRW0E",
                'active' => boolval(true),
                'subject_id' => "1",
            ],
            [
                'caption' => "PHP Tutorials",
                'description' => "iLearn the PHP programming language in this full course / tutorial. The course is designed for new programmers, and will introduce common programming topics using the PHP language.",
                'url' => "https://www.youtube.com/watch?v=OK_JCtrrv-c",
                'active' => boolval(true),
                'subject_id' => "2",
            ],
            [
                'caption' => "CSS Crash Course For Absolute Beginners",
                'description' => "In this video I will cram as much as possible about CSS. We will be looking at styles, selectors, declarations, etc. ",
                'url' => "https://www.youtube.com/watch?v=yfoY53QXEnI",
                'active' => boolval(true),
                'subject_id' => "3",
            ],
            [
                'caption' => "Android Development ",
                'description' => "In this video I will cram as much as possible about CSS. We will be looking at styles, selectors, declarations, etc. ",
                'url' => "https://www.youtube.com/watch?v=dFlPARW5IX8",
                'active' => boolval(true),
                'subject_id' => "4",
            ],
            [
                'caption' => "IOS For Beginners",
                'description' => "In this video I will cram as much as possible about CSS. We will be looking at styles, selectors, declarations, etc. ",
                'url' => "https://www.youtube.com/watch?v=VFixtdkZvtM",
                'active' => boolval(true),
                'subject_id' => "5",
            ],
            [
                'caption' => "Learn Python - Full Course for Beginners",
                'description' => "In this video I will cram as much as possible about CSS. We will be looking at styles, selectors, declarations, etc. ",
                'url' => "https://www.youtube.com/watch?v=rfscVS0vtbw",
                'active' => boolval(true),
                'subject_id' => "6",
            ],
            [
                'caption' => "Full Tutorial for Beginners",
                'description' => "In this video I will cram as much as possible about CSS. We will be looking at styles, selectors, declarations, etc. ",
                'url' => "https://www.youtube.com/watch?v=grEKMHGYyns",
                'active' => boolval(true),
                'subject_id' => "7",
            ],
            [
                'caption' => "How to make a Video Game in Unity - BASICS",
                'description' => "In this video I will cram as much as possible about CSS. We will be looking at styles, selectors, declarations, etc. ",
                'url' => "https://www.youtube.com/watch?v=IlKaB1etrik",
                'active' => boolval(true),
                'subject_id' => "8",
            ],
            [
                'caption' => "How to make a 2D Game in Unity",
                'description' => "In this video I will cram as much as possible about CSS. We will be looking at styles, selectors, declarations, etc. ",
                'url' => "https://www.youtube.com/watch?v=on9nwbZngyw",
                'active' => boolval(true),
                'subject_id' => "9",
            ],
            [
                'caption' => "Best Mobile Games",
                'description' => "In this video I will cram as much as possible about CSS. We will be looking at styles, selectors, declarations, etc. ",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "10",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "11",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "12",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "13",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "14",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "15",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "16",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "17",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "18",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "19",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "20",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "21",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "22",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "23",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "24",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "25",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "26",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "27",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "28",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "29",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "30",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "31",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "32",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "33",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "34",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "35",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "36",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "37",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "38",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "39",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "40",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "41",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "42",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "43",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "44",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "45",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "46",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "47",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "48",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "49",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "50",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "51",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "52",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "53",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "54",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "55",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "56",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "57",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "58",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "59",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "60",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "61",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "62",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "63",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "64",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "65",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "66",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "67",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "68",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "69",
            ],
            [
                'caption' => "Title Goes Here",
                'description' => "Description goes here",
                'url' => "https://www.youtube.com/watch?v=yYWHREAVOwE",
                'active' => boolval(true),
                'subject_id' => "70",
            ]
        ]);
    }
}
